/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_uceva_libcostos_lib_CostosProceso */

#ifndef _Included_co_uceva_libcostos_lib_CostosProceso
#define _Included_co_uceva_libcostos_lib_CostosProceso
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_uceva_libcostos_lib_CostosProceso
 * Method:    calcularCosto
 * Signature: ([FIF[F)F
 */
JNIEXPORT jfloat JNICALL Java_co_uceva_libcostos_lib_CostosProceso_calcularCosto
  (JNIEnv *, jobject, jfloatArray, jint, jfloat, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
