/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_uceva_libcostos_lib_PronosticoVentas */

#ifndef _Included_co_uceva_libcostos_lib_PronosticoVentas
#define _Included_co_uceva_libcostos_lib_PronosticoVentas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_uceva_libcostos_lib_PronosticoVentas
 * Method:    calcularPronostico
 * Signature: ([FII[F)V
 */
JNIEXPORT void JNICALL Java_co_uceva_libcostos_lib_PronosticoVentas_calcularPronostico
  (JNIEnv *, jobject, jfloatArray, jint, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
